{% set name = "sshfs" %}
{% set version = "2021.11.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sshfs-{{ version }}.tar.gz
  sha256: 34550f587e695781649ca830dbe23fabca4b4179f7eb047de855d2981f03c155

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - async-exit-stack ==1.0.1  # [py<37]
    - asyncssh >=2.7.1,<2.8
    - fsspec >=2021.8.1
    - python

test:
  imports:
    - sshfs
    - sshfs.pools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sshfs/
  summary: SSH Filesystem -- Async SSH/SFTP backend for fsspec
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isidentical
    - efiop
