{% set name = "sshfs" %}
{% set version = "2021.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sshfs-{{ version }}.tar.gz
  sha256: b2b4e0bc50eb00a9ffc3e7fd502bde1aa5fb8321cd8e85deac12e01050f7cae6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - async-exit-stack ==1.0.1  # [py<37]
    - asyncssh ==2.7.0
    - fsspec >=2021.8.1
    - python

test:
  imports:
    - sshfs
    - sshfs.pools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sshfs/
  summary: SSH Filesystem -- Async SSH/SFTP backend for fsspec
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isidentical
    - efiop
